services:
  postgres:
    image: postgres:16
    container_name: order-postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    ports:
      - "5432:5432"
    volumes:
      - order_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d orderdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks:
      - order_net

  order-service:
    container_name: order-service
    build:
      context: ../../backend/order-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orderdb
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_pass

      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/orderdb
      SPRING_FLYWAY_USER: order_user
      SPRING_FLYWAY_PASSWORD: order_pass

      SERVER_PORT: "8081"

      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health | grep -q 'UP'"]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    networks:
      - order_net
    spring:
  security:
    user:
      name: disabled
      password: disabled

networks:
  order_net:

volumes:
  order_pg_data:
